language: php
os: linux
dist: xenial

install:
  - travis_retry composer install

jobs:
  include:
   - php: 5.3 # Composer and PHPUnit require PHP 5.3.2+ to run, so we cannot test below 5.3
     dist: precise # PHP 5.3 is supported only on Precise.
   - php: 5.4
     dist: trusty  # PHP 5.4 is supported only on Trusty.
   - php: 5.5
     dist: trusty  # PHP 5.5 is supported only on Trusty.
   - php: 5.6
   - php: 7.0
   - php: 7.1
   - php: 7.2
   - php: 7.3
   - php: 7.4
   - php: nightly
     install: travis_retry composer config platform.php 7.4.0 && composer install
  fast_finish: true
  allow_failures:
   - php: nightly # PHP 8 is still in beta

services:
  - memcached
  - mysql

before_script:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

before_install:
  - phpenv config-rm xdebug.ini || return 0

script:
  - ./phpunit.sh
